# Generated by Django 2.1 on 2020-12-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhealth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
