# Generated by Django 2.1 on 2020-12-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhealth', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='tomato_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('disease_treatments', models.TextField(max_length=3000)),
                ('disease_control', models.TextField(max_length=3000)),
            ],
        ),
    ]
