# Generated by Django 2.1 on 2020-12-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmhealth', '0006_corn_plant_grapes_plant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='call_request',
        ),
    ]
