# Generated by Django 2.1 on 2020-12-29 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmhealth', '0007_delete_call_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tomato_plant',
            old_name='disease_control',
            new_name='disease_control1',
        ),
        migrations.RenameField(
            model_name='tomato_plant',
            old_name='disease_treatments',
            new_name='disease_control2',
        ),
        migrations.AddField(
            model_name='tomato_plant',
            name='disease_control3',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomato_plant',
            name='disease_control4',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomato_plant',
            name='disease_treatments1',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomato_plant',
            name='disease_treatments2',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomato_plant',
            name='disease_treatments3',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tomato_plant',
            name='disease_treatments4',
            field=models.TextField(default=django.utils.timezone.now, max_length=3000),
            preserve_default=False,
        ),
    ]
