# Generated by Django 2.1 on 2021-01-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmhealth', '0008_auto_20201229_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='pic_uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
