# Generated by Django 2.1 on 2021-01-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmhealth', '0009_auto_20210103_0919'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pic_uploader',
            new_name='pic_saved',
        ),
    ]
